// Code generated by protoc-gen-go. DO NOT EDIT.
// source: internal/infra/grpc/protofiles/order.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateOrderRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Price                float32  `protobuf:"fixed32,2,opt,name=price,proto3" json:"price,omitempty"`
	Tax                  float32  `protobuf:"fixed32,3,opt,name=tax,proto3" json:"tax,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateOrderRequest) Reset()         { *m = CreateOrderRequest{} }
func (m *CreateOrderRequest) String() string { return proto.CompactTextString(m) }
func (*CreateOrderRequest) ProtoMessage()    {}
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a81083cb550ac9a5, []int{0}
}

func (m *CreateOrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateOrderRequest.Unmarshal(m, b)
}
func (m *CreateOrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateOrderRequest.Marshal(b, m, deterministic)
}
func (m *CreateOrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateOrderRequest.Merge(m, src)
}
func (m *CreateOrderRequest) XXX_Size() int {
	return xxx_messageInfo_CreateOrderRequest.Size(m)
}
func (m *CreateOrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateOrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateOrderRequest proto.InternalMessageInfo

func (m *CreateOrderRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CreateOrderRequest) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *CreateOrderRequest) GetTax() float32 {
	if m != nil {
		return m.Tax
	}
	return 0
}

type CreateOrderResponse struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Price                float32  `protobuf:"fixed32,2,opt,name=price,proto3" json:"price,omitempty"`
	Tax                  float32  `protobuf:"fixed32,3,opt,name=tax,proto3" json:"tax,omitempty"`
	FinalPrice           float32  `protobuf:"fixed32,4,opt,name=final_price,json=finalPrice,proto3" json:"final_price,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateOrderResponse) Reset()         { *m = CreateOrderResponse{} }
func (m *CreateOrderResponse) String() string { return proto.CompactTextString(m) }
func (*CreateOrderResponse) ProtoMessage()    {}
func (*CreateOrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a81083cb550ac9a5, []int{1}
}

func (m *CreateOrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateOrderResponse.Unmarshal(m, b)
}
func (m *CreateOrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateOrderResponse.Marshal(b, m, deterministic)
}
func (m *CreateOrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateOrderResponse.Merge(m, src)
}
func (m *CreateOrderResponse) XXX_Size() int {
	return xxx_messageInfo_CreateOrderResponse.Size(m)
}
func (m *CreateOrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateOrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateOrderResponse proto.InternalMessageInfo

func (m *CreateOrderResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CreateOrderResponse) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *CreateOrderResponse) GetTax() float32 {
	if m != nil {
		return m.Tax
	}
	return 0
}

func (m *CreateOrderResponse) GetFinalPrice() float32 {
	if m != nil {
		return m.FinalPrice
	}
	return 0
}

func init() {
	proto.RegisterType((*CreateOrderRequest)(nil), "pb.CreateOrderRequest")
	proto.RegisterType((*CreateOrderResponse)(nil), "pb.CreateOrderResponse")
}

func init() {
	proto.RegisterFile("internal/infra/grpc/protofiles/order.proto", fileDescriptor_a81083cb550ac9a5)
}

var fileDescriptor_a81083cb550ac9a5 = []byte{
	// 214 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x90, 0x31, 0x4b, 0xc7, 0x30,
	0x10, 0xc5, 0x69, 0xaa, 0x82, 0x57, 0x11, 0x89, 0x52, 0x83, 0x8b, 0xa5, 0x53, 0x71, 0x68, 0x40,
	0x77, 0x07, 0x5d, 0x45, 0xa5, 0x6e, 0x2e, 0x92, 0xb4, 0x57, 0x09, 0x94, 0x24, 0x5e, 0xa2, 0xf8,
	0xf1, 0x25, 0xe9, 0xa2, 0xd4, 0xe9, 0xbf, 0x25, 0xbf, 0x77, 0xbc, 0x77, 0xf7, 0xe0, 0xca, 0xd8,
	0x88, 0x64, 0xd5, 0x22, 0x8d, 0x9d, 0x49, 0xc9, 0x77, 0xf2, 0xa3, 0xf4, 0xe4, 0xa2, 0x9b, 0xcd,
	0x82, 0x41, 0x3a, 0x9a, 0x90, 0xfa, 0x0c, 0x38, 0xf3, 0xba, 0x7d, 0x00, 0x7e, 0x4f, 0xa8, 0x22,
	0x3e, 0x25, 0x61, 0xc0, 0x8f, 0x4f, 0x0c, 0x91, 0x1f, 0x03, 0x33, 0x93, 0x28, 0x9a, 0xa2, 0x3b,
	0x1c, 0x98, 0x99, 0xf8, 0x19, 0xec, 0x7b, 0x32, 0x23, 0x0a, 0xd6, 0x14, 0x1d, 0x1b, 0xd6, 0x0f,
	0x3f, 0x81, 0x32, 0xaa, 0x6f, 0x51, 0x66, 0x96, 0x9e, 0xad, 0x85, 0xd3, 0x3f, 0x6e, 0xc1, 0x3b,
	0x1b, 0x70, 0x57, 0x3b, 0x7e, 0x09, 0xd5, 0x6c, 0xac, 0x5a, 0xde, 0xd6, 0xe9, 0xbd, 0xac, 0x40,
	0x46, 0xcf, 0x89, 0x5c, 0x3f, 0xc2, 0x51, 0x4e, 0x7a, 0x41, 0xfa, 0x4a, 0x16, 0xb7, 0x50, 0xfd,
	0xca, 0xe7, 0x75, 0xef, 0x75, 0xbf, 0x3d, 0xef, 0xe2, 0x7c, 0xc3, 0xd7, 0x45, 0xef, 0xc4, 0x6b,
	0xfd, 0x6f, 0x7f, 0x5a, 0x1f, 0xe4, 0xca, 0x6e, 0x7e, 0x02, 0x00, 0x00, 0xff, 0xff, 0xf2, 0xf8,
	0x53, 0x92, 0x60, 0x01, 0x00, 0x00,
}
